on:
  workflow_dispatch

jobs:
  generatereport:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    # install dependencies
    - name: dependencies
      run: pip install pandas

    # generate the report
    - name: Generate report
      run: |
        cd reports/
        python get_links.py

    # start a pull request for it
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: 'autodraft report content'
        draft: true
        title: EC Report
